{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "credbridge.fullname" . }}
  labels:
    {{- include "credbridge.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    {{- if .Values.externalSecrets.secretStore.create }}
    name: {{ include "credbridge.fullname" . }}
    {{- else }}
    name: {{ .Values.externalSecrets.secretStore.existingName | quote }}
    {{- end }}
    kind: {{ .Values.externalSecrets.secretStore.kind }}
  target:
    name: {{ include "credbridge.fullname" . }}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        {{- range $config := .Values.vault.secrets.keys }}
        {{ $config.secretKey | upper }}: "{{ `{{ .` }}{{ $config.secretKey }}{{ ` }}` }}"
        {{- end }}
  data:
  {{- range $config := .Values.vault.secrets.keys }}
  - secretKey: {{ $config.secretKey }}
    remoteRef:
      {{- if $config.path }}
      key: {{ tpl $config.path $ }}
      {{- else }}
      key: {{ tpl $.Values.vault.secrets.basePath $ }}/{{ $config.key }}
      {{- end }}
      property: {{ $config.property }}
  {{- end }}
{{- end }}